import { CrudityOptions } from "./interfaces/CrudityOptions";
import { OpenApi3 } from "./interfaces/OpenApi3";
import npmPackage from "../package.json";
import { Request } from "express";

function getEndPoint(req: Request) {
  return req.protocol + "://" + req.get("host") + req.baseUrl;
}

export class Swagger {
  constructor(
    private req: Request,
    private resourceName: string,
    private options: CrudityOptions
  ) {}

  generate(): OpenApi3 {
    return {
      openapi: "3.0.3",
      info: {
        title: `Crudity ${this.resourceName}`,
        version: npmPackage.version,
        description: `The RESTful API generated by Crudity for resource '${this.resourceName}'`,
        contact: npmPackage.author,
      },
      servers: [
        {
          url: getEndPoint(this.req),
        },
      ],
      paths: {
        "/": {
          description: `CRUD on ${this.resourceName}`,
          get: {
            description: `Return a list of ${this.resourceName}`,
            responses: {
              default: { description: "truc bidule" },
            },
          },
          post: {
            description: `Create new ${this.resourceName}`,
            responses: {
              default: { description: "truc bidule" },
            },
          },
          delete: {
            description: `Delete ${this.resourceName}`,
            responses: {
              default: { description: "truc bidule" },
            },
          },
        },
        "/{id}": {
          description: `CRUD on a specific instance given by id among all ${this.resourceName}`,
          get: {
            description: `Return a specific instance among all ${this.resourceName}`,
            responses: {
              default: { description: "truc bidule" },
            },
          },
          put: {
            description: `Replace new ${this.resourceName}`,
            responses: {
              default: { description: "truc bidule" },
            },
          },
          patch: {
            description: `Update new ${this.resourceName}`,
            responses: {
              default: { description: "truc bidule" },
            },
          },
          delete: {
            description: `Delete ${this.resourceName}`,
            responses: {
              default: { description: "truc bidule" },
            },
          },
        },
      },
    };
  }
}
